### ISSUE TITLE
ECS-5 Distribution

### ISSUE THREAD

**Issue by jasonwr** [Netflix/vizceral#12]
@jrsquared can you provide a transpiled copy of the distributed sources from ECMAScript-6 to ECMAScript-5? I would greatly appreciate this (older browser compatibility). Also thank you so much for maintaining vizceral. I really appreciate all your hard work. See note:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

I realize I can do this with **babel** but was concerned about doing so because you are using AMD and Webpack and it looks like you're doing some custom stuff in your source.

**Comment by jrsquared** [comment]
There are two options that already exist:

1. The transpiled copy is in the npm package /dist directory, so if you npm install the package, you'll get the transpiled sources.
2. If you clone the repo, you can run `npm install && npm run build` and it will build the transpiled dist for you on your local machine.

Would either of these options work for you? I am not a huge fan of including output files in source control.

**Comment by jasonwr** [comment]
@jrsquared I'm looking at the dist and do not see the transpiled copy for ECMAScript 5. I just downloaded the latest and greatest. Under dist/ I have:
`
vizceral.js
vizceral.js.map
vizceral.min.js
` 
Also when I run the `npm install && npm run build` I get a file ending in *.worker.js Is this the ECMAScript 5 transpiled file? I grepped for vizceral in this file and I didn't receive any matches.

**Comment by jasonwr** [comment]
@jrsquared It's been quiet for a few hours. Did you get a chance to read my reply? Thank you.

**Comment by jrsquared** [comment]
@jasonwr I did get a chance to read your reply.  While I do my best to reply to comments, my full time job is not maintaining the open source project; please see https://github.com/turbolinks/turbolinks/pull/124#issuecomment-239826060 for a very well-written comment about maintaining open source projects.

That being said, dist/vizceral.js (and dist/vizceral.min.js) is the transpiled js.  The .worker.js file is the worker that handles laying out the graph and you should never need to include that directly in your project.

I have pushed an update 32484a5 that will make Vizceral a named define if included in a script tag, so that should make what you were trying above work better.

However, Firefox 31 was released [over two years ago](https://www.mozilla.org/en-US/firefox/31.0/releasenotes/).  With all major browsers supporting auto-update mechanisms, we only support the most recent versions of Chrome, Firefox, and Safari.

You are welcome to try to make things work with Firefox 31, and if changes are required, open pull requests.  If the changes don't break things for the supported modern browsers, I'd be happy to review them.

I am going to close this bug since vizceral is outputting transpiled javascript.  If you are still having trouble using vizceral with a <script> tag, please open a different issue.

**Comment by jasonwr** [comment]
@jrsquared Thanks for your help. I really appreciate it.
