### ISSUE TITLE
Less CPU consumption?

### ISSUE THREAD

**Issue by rtoma** [Netflix/vizceral#18]
Hi guys,
Thanks for opensourcing such a great visualisation tool!
Is there a way to reduce the amount of CPU cycles needed for running it?
Chrome on OSX takes 300% running the example and my fan goes crazy.

**Comment by jrsquared** [comment]
There are many things that can be done to improve performance and CPU usage:

* Use three.js [BufferGeometry](http://threejs.org/docs/#Reference/Core/BufferGeometry) whenever possible, I have switched to using them in multiple places, but I'm sure there's more.
* Move the traffic dot calculation to the shaders on the GPU.
* Have all the connections share a single particle system instead of each having their own.

You are welcome to try to take a stab at improving CPU performance.

For what it's worth, I'm on a Mid-2015 15" Macbook Pro, and it uses between 70-110% CPU.

**Comment by hekike** [comment]
@jrsquared do you have an implementation documentation or something that can help me to understand the architecture better? I would like to work on this and decrease CPU usage, but seems to be complicated without help.

**Comment by jrsquared** [comment]
I do not have an implementation document. If you have any specific questions, I'd be happy to try to answer them. Most of the CPU/GPU usage is down in THREE.js, so most gains would be from understanding how THREE.js works better and optimizing for that. If you really are willing to work on CPU usage, I'd be happy to walk you through some of the architecture over Skype or something. Feel free to email me.

**Comment by hekike** [comment]
@jrsquared thanks for the help! I spent the last couple of days to dig deeper in vizceral. A Skype call would be really helpful, but first I would like to spend more time with understanding it. I'll ping you early January.

**Comment by anrub** [comment]
@hekike did you succeed in optimzing? I want to optimize that as well, so i will be digging into the THREE.js usage, maybe you already have some spots?

**Comment by hekike** [comment]
@anrub no, finally I didn't use vizceral in my project.

**Comment by anrub** [comment]
@hekike Did you find something else for visualizing?

**Comment by hekike** [comment]
@anrub we are using [Cytoscape.js](http://js.cytoscape.org/) to visualize infrastructures, you can take a look how it works: https://trace.risingstack.com

It doesn't have that nice animation than `vizceral`, we use colors, line weights, and other visual elements to explain data.
