### ISSUE TITLE
Nodes aligned in a vertical line even with connections between them

### ISSUE THREAD

**Issue by JohnRambo** [Netflix/vizceral#29]
Seems like quite often I get all the nodes aligned in a vertical line, even though there are connections between them. This doesn't seem to happen in the examples. What are some parameters I could tweak to make it better?

**Comment by jrsquared** [comment]
Could you please share a data set that exhibits this behavior when you do not expect it?

**Comment by jasonwr** [comment]
@JohnRambo a screenshot would also help.

**Comment by jasonwr** [comment]
@jrsquared I don't have a screenshot on me but can attest to the fact that if there are many nodes within a single view the graph on the canvas can become very convoluted and difficult to read. Is there a spacing algorithm that respaces and scrunches nodes because if only a few nodes are added they fill up the graph and are spaced out? Rather than a relative width is there a way to set an absolute positioning on the nodes? That way if the nodes fill out the canvas I can simply add the overflow scroll CSS property. Thank you.

**Comment by jrsquared** [comment]
@jasonwr Yes, that is correct. There is not a different spacing algorithm because we currently do not need to support more than a few hundred nodes. I will gladly accept pull requests that contain different layout algorithms! Also, this is a different topic than the OP opened with, so please start a new issue if you want to address the density of nodes.

**Comment by jasonwr** [comment]
@jrsquared That's all I need to know for now. I'll count the number of nodes I'm displaying and try to play with it some more. Can you tell me where to look (i.e. give me some pointers)?

![pointers](https://cloud.githubusercontent.com/assets/305999/19084536/f682bc8c-8a34-11e6-8e4a-8e12f1d55c9e.png)

**Comment by jrsquared** [comment]
The current layout algorithm is just loaded via  [layoutWorker.js](https://github.com/Netflix/vizceral/blob/master/src/base/layoutWorker.js). If you want to create a new layout algorithm, layoutWorker could be parameterized and call whichever algorithm is requested.

**Comment by jasonwr** [comment]
@jrsquared Thanks!

**Comment by JohnRambo** [comment]
Sorry my question was vague on purpose, I would have to go through hoops of what can and what can't be shared publicly. I think the answer to this is modification of the layout algorithm, if I ever get back to this I will send a pull request. Thanks

**Comment by jrsquared** [comment]
Great, looking forward to it! Closing for now...
