### ISSUE TITLE
Vanilla JS Example - new TypeError

### ISSUE THREAD

**Issue by jasonwr** [Netflix/vizceral#31]
@jrsquared 
Just pulled down Vizceral 3.0.5 and transpiled via npm the sources to ECMAScript 5. Receiving the following error in Firefox 40 (Firebug):

TypeError: childrenIds.includes is not a function
* return childrenIds.includes(c.id);

This is coming from line 67827

What I did was hack the transpiled source for that line.

BEFORE:
return childrenIds.includes(c.id);

AFTER:
return function( ) {return childrenIds.includes(c.id));

I'm not sure where to make this change in the source but the hack works for me as a temporary solution. Just wanted to put this on your radar.

**Comment by jrsquared** [comment]
Vizceral only officially supports the latest version of Chrome, and sanity checking on the latest versions of Safari and Firefox, and Firefox 49 does not appear to exhibit this error. Closing since the bug is in a browser that is nine versions and one year behind.

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes), support for `Array.prototype.includes` was added in version 43.

Even with that in mind, your hack does not fix the problem, it just hides the problem. Instead of returning true or false if a child id is in `childrenIds`, the function now returns a function, which is always truthy.
