### ISSUE TITLE
Node and connection select-ability broken after update to 4.0.2

### ISSUE THREAD

**Issue by aSqrd-eSqrd** [Netflix/vizceral#37]
I've been working from the vizceral-example project and have really appreciated the last couple of weeks of updates, especially the more in-depth documentation.  At any rate, I am just experimenting with adding some of my own filters and so my work is basically stock.  I changed the package.json for vizceral-example to require use the vizceral-react ver ~4.0.0, which pulls vizceral ver ~4.0.0.

This caused the "click-ability" of the nodes and connections in a region view to no longer even be an option.  I tried a clean clone of vizceral-example and via "npm list vizceral" which reports:

```
└─┬ vizceral-react@3.0.4
  └── vizceral@3.0.9 
```

When I change the package.json of vizceral-example to using viceral-react@4.0.0 (output from "npm link vizceral")
```
└─┬ vizceral-react@4.0.0
  └── vizceral@4.0.2 
```
The only "clickable" items are those in the global view.  Once in the region view no connection or node is clickable.

Thanks for the great work and a beautiful tool.

**Comment by jrsquared** [comment]
Vizceral had bumped a major version because there were breaking changes. I have since updated vizceral-example (Netflix/vizceral-example@0abcdb7fc623251805b8adfa78118cddaea8e559) to support the new changes necessary in the data format.

The biggest change, and the one that was causing the third view to not load, was that I removed the implicit 'zoomability' of the RegionTrafficGraph.  You now need to explicitly state that you want nodes to be rendered as a FocusedTrafficGraph to get the same effect.  This builds a foundation for much more configurability and customization of the third-level view (and follow the same model of the rest of the views)
