### ISSUE TITLE
Request for advice/help with debugging

### ISSUE THREAD

**Issue by aSqrd-eSqrd** [Netflix/vizceral#46]
@jrsquared,
I have been trying to understand how the left-to-right tree layout works in hope of figuring out why when sometimes when I drill down to level-3 (focusedChild style) the node drilled into has all of its incoming and outgoing connected nodes stacked directly on top of the node (i.e., all the little circle nodes are stacked on top of the donut graph node), but for the life of me I cannot find a way to debug in to the ltrTreeLayout code from my top-level wrapper.

The vizceral-example is the bases of my top-layer, then I make use of vizceral-react and vizceral all locally linked using npm.  I've made sure to generate source-maps and load them in to Chrome, but they only point to the vizceral-react "bundle" and I can't seem to get all the way down into the vizceral library bundle.

I've even tried configuring VS code as the debugging interface/iDE, but at this point after 5 frustrating days of failed configurations and settings in VS code and webpack.  I'm ready to stop being stubborn and ask for help.

- What do you use for debugging (i.e. an IDE?, a browser?, something else entirely?)
- How would you debug, specifically set breakpoints, in ltrTreeLayout?
- Is it even possible to set a breakpoint that can be reached in say  ltrTreeLayout or ltrTreeLayoutWorker when running vizceral-example as the top-level?
- Do you "disable" the web-worker so that the position setting code isn't webpack'ed into an obfuscated nightmare?

Any advice would be greatly appreciated.

Thanks

**Comment by jrsquared** [comment]
That is unfortunate that you are running into that situation... We don't have any circular dependencies in our graphs so maybe that could be causing some problems? I'm not sure.

As far as debugging a local project, the workflow that I use (if anyone can think of a better one, *please* give suggestions)
1. In `vizceral` run `npm link` (Create a link to the vizceral project)
2. In `vizceral-react` run `npm link vizceral` (Use the linked vizceral project)
3. In `vizceral-react` run `npm link` (Create a link to the vizceral-react project)
4. Modify vizceral-react/src/vizceral.jsx to import vizceral source
Line 5: `import VizceralGraph from 'vizceral'` --> `import VizceralGraph from 'vizceral/src/vizceral.js'`
5. In `vizceral-example` run `npm link vizceral-react` (Use the linked vizceral-react project)
6. Modify vizceral-example/src/components/trafficFlow.jsx to import vizceral-react source
Line 7: `import Vizceral from 'vizceral-react'` -> `import Vizceral from 'vizceral-react/src/vizceral.jsx'`

Now, when you run `npm run dev` in the example project, it should transpile all the code and generate a source map for everything, making debugging in Chrome straightforward.

As far as debugging the layout worker, that's a little more tricky because the worker is only loaded on demand, so it's difficult to put breakpoints.  You can either put in `debugger` statements in the worker so Chrome will break on them, or move the code out of a worker for development, then put it back in the worker when you're done.

Justin

**Comment by aSqrd-eSqrd** [comment]
@jrsquared 

Thanks so much!  Your steps plus "un-web-worker-ing" the worker code allows full debug via Chrome.  It let me find where things go haywire and all the nodes get stacked on top of each other in the level-3 node detail "zoom" level.  It is a relief to have a where, now just to figure out the why it is happening.

Again, thank you for your work and assistance.
