### ISSUE TITLE
Getting "Region Loading" whenever a region does not have source of internet.

### ISSUE THREAD

**Issue by bcronrath** [Netflix/vizceral#56]
Is this by design for the Vizceral tool?  Basically what I am observing is that let's say I have a connections array telling me something like this:

Source   Destination
INTERNET    Region A
INTERNET    Region B
Region C      Region A

In this case Region C just displays as "Region Loading" but still shows the dots flowing from C to A.  Is this by design that INTERNET should always be the source to a region in order for it to be displayed?  Or perhaps is there something else I can look into?  I've double checked that Region C is included in the Nodes array as well.

**Comment by jrsquared** [comment]
Yes, this is by design. Since the global graph is a collection of regional graphs for our use case, we show the node in the global view as 'Region Loading' until the node has nodes under it.

https://github.com/Netflix/vizceral/blob/master/src/global/globalNode.js#L33

There is definitely room for improvement here for use cases that want to use this global view without needing to drill into each node. If this is indeed functionality you want, feel free to submit a PR; I would be happy to look it over.

**Comment by rehanann** [comment]
hi;
I am using vizceral example  and using sample_data.json short version and having 2 zones for demo.
i have 2 region A and B, how do I setup in json if I failover all traffic to region B?
can you please provide this option?
