### ISSUE TITLE
Selecting a directed edge

### ISSUE THREAD

**Issue by apoorv007** [Netflix/vizceral#68]
I am unable to find a way to specify the direction when selecting an edge. If there is traffic from A -> B, and also from B -> A, looks like it chooses the direction with more traffic.

How about adding the capability to specify the direction depending upon which half of the edge was clicked?

**Comment by jrsquared** [comment]
We don't have bidirectional connections so this isn't a use case we have thought about. Would definitely welcome a PR for something like this though!

**Comment by aSqrd-eSqrd** [comment]
My use case involves bi-directional data flow.  Vizceral out of the box will show particles traveling in both directions simultaneously.

It is subtle to see the particles flying in both directions if one direction has a significantly higher volume than the other with respect to the `maxVolume` of course.  That is if one is "bigger" (non-trivial difference) than the other but they are both small with respect to `maxVolume` you should be able to see the particles traveling in both directions.

If you want to prove to yourself that both directions are flowing/producing particles change the metric of one direction to something different so that the particles will have different colors, e.g.
```json
"connections": [
    {"source": "A", "target": "B", "metrics": {"normal": 117}},
    {"source": "B", "target": "A", "metrics": {"warning": 12}}
]
```
I would be wary of hiding the traffic on a bi-directional connection.  If one direction is so much more important that you would hide the very existence of the reverse flow... do you even need the connection you are willing to hide?

**Comment by jrsquared** [comment]
Again, thank you for the well written response @aSqrd-eSqrd.
